apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: "${class_name}"  # needs to be unique per namespace
  namespace: "${namespace_name}"
spec:
  provider: azure
  secretObjects:                            # secretObjects defines the desired state of synced K8s secret objects
  - secretName: ingress-tls-csi
    type: kubernetes.io/tls
    data: 
    - objectName: "${cert_name}"
      key: tls.key
    - objectName: "${cert_name}"
      key: tls.crt
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"          
    clientID: "${clientID}" # Setting this to use workload identity
    keyvaultName: "${key_vault_name}"       # Set to the name of your key vault
    cloudName: ""                         # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects: |
      array:
        - |
          objectName: "${cert_name}"
          objectType: secret
    tenantId: "${tenant_id}"        # The tenant ID of the key vault